FROM node:24-alpine

WORKDIR /app

# Install dependencies
COPY package.json package-lock.json tsconfig.json ./
RUN npm ci

# Copy the rest of the code
COPY . .

# Expose application port
EXPOSE 4000

# Start in development mode
CMD ["npm", "run", "dev"]
